app = 'iroh-bot'
primary_region = 'iad'

[build]

[env]
  NODE_ENV = 'production'
  LOG_LEVEL = 'info'

[processes]
  app = 'sh -c "node dist/deploy-commands.js && node dist/bot.js"'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  processes = ['app']
  min_machines_running = 1
