app = 'iroh-bot'
primary_region = 'iad'

[build]

[deploy]
  release_command = 'node dist/deploy-commands.js'

[env]
  NODE_ENV = 'production'
  LOG_LEVEL = 'info'

[processes]
  app = 'node dist/bot.js'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '512mb'
  processes = ['app']

[[restart]]
  policy = 'always'
  retries = 5
  processes = ['app']
